name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "非常感谢你的提问，我们会尽快查清对应的问题并给出解决方案。 Thank you very much for your question. We will find out the corresponding problem as soon as possible and provide a solution."
        pr-message: "非常感谢你能够参与到这个项目当中，希望你能够喜欢这个项目所实现的一些功能。 Thank you very much for participating in this project. I hope you'll like some of the functions implemented in this project."
